Missing header file added.
* This prevents error messages like this: "hardware/qcom-caf/msm8994/audio/post_proc/effect_api.c:108:5: error: call to undeclared library function 'snprintf' with type 'int (char *, unsigned long, const char *, ...)'".

Change-Id: I10635ae8d8f730efc4f084fb3aec78981ff2c3a1